version: "3.9"

services:
  postgres:
    image: postgres:12-alpine
    container_name: trpc_db
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASS}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres:
